### ISSUE TITLE
add to marketplace

### ISSUE THREAD

**Issue by andrinmeier** [andrinmeier/unofficial-d2lang-confluence-plugin#12]

**Comment by andrinmeier** [comment]
Apparently no apps can be made public anymore.

**Comment by derekg52** [comment]
> Apparently no apps can be made public anymore.

Hi @andrinmeier - we were looking into D2, specifically for our Confluence at work.  Can you explain more about your comment that "no apps can be made public anymore"?  We'd really like to use your plugin, but it seems it won't pass an audit by not being available on the Atlassian Marketplace.  Thanks in advance!

**Comment by andrinmeier** [comment]
The plugin's a server app and according to Atlassian, no new server apps can be published on the marketplace: https://community.developer.atlassian.com/t/reminder-we-will-stop-accepting-new-server-app-submissions-from-may-1-exceptions-to-be-made-for-bamboo-and-crowd/47042/7. Data Center Apps can be published, altough I haven't looked into them yet.

You can install the plugin manually though if you like, using the JAR (or you can build the JAR yourself based on the source coude).

**Comment by derekg52** [comment]
@andrinmeier I appreciate the response, and thanks for the Atlassian link.  At least in our particular case, we are using the data center version.  If you ever felt compelled to publish a data center version, let me know; I'd be interested in trying it out.  Thanks!
